In [3]:
import numpy as np
# 创建简单的列表
a = [1, 2, 3, 4]
# 将列表转换为数组
b = np.array(a)

In [4]:
b.size

4

In [6]:
b.shape

(4,)

In [5]:
b.ndim

1

In [7]:
b.ndim

1

In [8]:
b.dtype

dtype('int32')

In [11]:
array_one = np.ones([10, 10])

In [13]:
array_zero = np.zeros([10, 10])

In [14]:
np.random.rand(10, 10)

array([[ 0.01240586,  0.44328226,  0.09768594,  0.75079356,  0.55878747,
         0.97616115,  0.5020638 ,  0.20401104,  0.41683209,  0.45862572],
       [ 0.51748642,  0.95596093,  0.42049882,  0.62917307,  0.40359322,
         0.77764981,  0.99155398,  0.75078411,  0.61676435,  0.09081167],
       [ 0.64584664,  0.11926398,  0.80500538,  0.96312115,  0.74371221,
         0.10625502,  0.21586638,  0.89553959,  0.44231194,  0.01680601],
       [ 0.30826261,  0.24741877,  0.29409855,  0.30383142,  0.66410442,
         0.01908584,  0.65075492,  0.34019716,  0.19305248,  0.84576161],
       [ 0.42543059,  0.5935522 ,  0.31988689,  0.31654184,  0.26571332,
         0.50020633,  0.14996915,  0.80997073,  0.5386504 ,  0.11557889],
       [ 0.34022142,  0.91081713,  0.3660851 ,  0.53767171,  0.14981551,
         0.18872909,  0.03943511,  0.9466499 ,  0.38786855,  0.92933147],
       [ 0.97489469,  0.56481739,  0.98599655,  0.25025588,  0.50963121,
         0.34088683,  0.25960017,  0.39423197

In [16]:
np.random.uniform(0, 100)

55.56281109869696

In [18]:
np.random.randint(0, 100)

67

In [20]:
np.random.normal(1.75, 0.1, (2, 3))

array([[ 1.70029161,  1.7109314 ,  1.67621405],
       [ 1.7794016 ,  1.69620397,  1.76238211]])

In [22]:
# 正态生成4行5列的二维数组
arr = np.random.normal(1.75, 0.1, (4, 5))
print(arr)
# 截取第1至2行的第2至3列(从第0行算起)
after_arr = arr[1:3, 2:4]
print(after_arr)

[[ 1.82763073  1.79554911  1.64671333  1.83963655  1.7466017 ]
 [ 1.7485455   1.68281227  1.80108616  1.76919296  1.77893335]
 [ 1.6726146   1.71386203  1.63498555  1.78792942  1.91573263]
 [ 1.75191745  1.72270713  1.81768576  1.686838    1.56433962]]
[[ 1.80108616  1.76919296]
 [ 1.63498555  1.78792942]]


In [27]:
print("reshape函数的使用!")
one_20 = np.ones([20])
print("-->1行20列<--")
print (one_20)

one_4_5 = one_20.reshape([4, 5])
print("-->4行5列<--")
print (one_4_5)

reshape函数的使用!
-->1行20列<--
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]
-->4行5列<--
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [30]:

import numpy as np
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
stus_score > 80


array([[False,  True],
       [ True,  True],
       [ True, False],
       [ True,  True],
       [False,  True]], dtype=bool)

In [31]:
import numpy as np
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
np.where(stus_score < 80, 0, 90)

array([[90, 90],
       [90, 90],
       [90,  0],
       [90, 90],
       [ 0, 90]])

In [32]:
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
# 求每一列的最大值(0表示列)
print("每一列的最大值为:")
result = np.amax(stus_score, axis=0)
print(result)

print("每一行的最大值为:")
result = np.amax(stus_score, axis=1)
print(result)


每一列的最大值为:
[86 88]
每一行的最大值为:
[88 82 84 86 81]


In [34]:
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
# 求每一行的最小值(0表示列)
print("每一列的最小值为:")
result = np.amin(stus_score, axis=0)
print(result)

# 求每一行的最小值(1表示行)
print("每一行的最小值为:")
result = np.amin(stus_score, axis=1)
print(result)

每一列的最小值为:
[75 75]
每一行的最小值为:
[80 81 75 83 75]


In [35]:
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
# 求每一行的平均值(0表示列)
print("每一列的平均值:")
result = np.mean(stus_score, axis=0)
print(result)

# 求每一行的平均值(1表示行)
print("每一行的平均值:")
result = np.mean(stus_score, axis=1)
print(result)

每一列的平均值:
[ 81.4  81.6]
每一行的平均值:
[ 84.   81.5  79.5  84.5  78. ]


In [36]:
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
# 求每一行的方差(0表示列)
print("每一列的方差:")
result = np.std(stus_score, axis=0)
print(result)

# 求每一行的方差(1表示行)
print("每一行的方差:")
result = np.std(stus_score, axis=1)
print(result)

每一列的方差:
[ 3.77359245  4.1761226 ]
每一行的方差:
[ 4.   0.5  4.5  1.5  3. ]


In [37]:
stus_score = np.array([[80, 88], [82, 81], [84, 75], [86, 83], [75, 81]])
print("加分前:")
print(stus_score)

# 为所有平时成绩都加5分
stus_score[:, 0] = stus_score[:, 0]+5
print("加分后:")
print(stus_score)


加分前:
[[80 88]
 [82 81]
 [84 75]
 [86 83]
 [75 81]]
加分后:
[[85 88]
 [87 81]
 [89 75]
 [91 83]
 [80 81]]
